### ISSUE TITLE
d'Aboville System

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#155]
Reports parent menu, this is the first of many reports to include.

### Description
https://en.wikipedia.org/wiki/Genealogical_numbering_systems#d'Aboville_System

**Comment by curtisdelicata** [comment]
Backend for generating the trees to be displayed in text on the page.

**Comment by jacob-liu-g** [comment]
@everyone you got scammed, please check @curtisdelicata 's Linkedin profile. He is fraud and liar. He never pay for developers. 

He runs fake business called FamilyTree365. He lies developers to contribute the project for a week and pretend to pay after a week but he disappears after receiving PR.

I should alert other honest developers and customers that you should never support Curtis Delicata since he is a fraud.

I can share you more evidence if anybody interested.

https://www.linkedin.com/feed/update/urn:li:activity:6906662303572606976/

![image](https://user-images.githubusercontent.com/72995735/157096643-3d6dd048-5dcf-47ca-b5c4-f97d4064134b.png)
