### ISSUE TITLE
Improve gedcom export

### ISSUE THREAD

**Issue by curtisdelicata** [liberu-genealogy/genealogy-old#1876]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/familytree365)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by jacob-liu-g** [comment]
@superdev412   you are scammed, please check @curtisdelicata 's Linkedin profile. He is fraud and liar. He never pay for developers. 

He runs fake business called FamilyTree365. He lies developers to contribute the project for a week and pretend to pay after a week but he disappears after receiving PR.

I should alert other honest developers and customers that you should never support Curtis Delicata since he is a fraud.

I can share you more evidence if anybody interested.

https://www.linkedin.com/feed/update/urn:li:activity:6906662303572606976/

![image](https://user-images.githubusercontent.com/72995735/157096643-3d6dd048-5dcf-47ca-b5c4-f97d4064134b.png)

**Comment by curtisdelicata** [comment]
Gedcom export should process the database and create a valid gedcom file. It should only be accessible by the logged in user who created it

**Comment by Dip-Ghosh** [comment]
Can you please elaborate on the task? As I am a beginner in this project it will be a great help if you exaggerate the task and tell me in detail about this particular issue

**Comment by curtisdelicata** [comment]
Gedcom export needs to download a gedcom containing data from the database. The opposite of import. Basic code is already added.
